// /config/templates.config.js

module.exports = {
    defaultTemplates: {
        basic: "-9DirnjVO1FlbEW1lN8jITBESrTsQKEM_BoZ1ey_0mk",
        creatorRegistration: "BKVvTSXmmJni-L82irZfPFXWWJLBcdvbxS34jP1FTG8", 
        associatedURLOnWeb: "eVTn36AY0JdLI_jzj9FivxrxtvlkVQIPI5ma-1x0E2c",
        text: "VJvEIk7z6CHsfxFP3QEWbr8Q0BsewQjDALN4eRhD7F4",
        image: "AkZnE1VckJJlRamgNJuIGE7KrYwDcCciWOMrMh68V4o",
        video: "G73WplyxpNDOgDSFO6CP3O6hZXq8kNJXxkCqx3sgd1s",
        post: "op6y-d_6bqivJ2a2oWQnbylD4X_LH6eQyR6rCGqtVZ8",
        podcast: "MojoZlLKaH-cHy_HbaGBlBA7Mxzf8dJl4MQZzFQAkMY",
        jfkFilesPageOfDocument: "WP-tZ5nwxrMwr5wKHazTFUtGLRd6nQWRBl8E63Kqufg",
        jfkFilesDocument: "d3xoxXQ8hUlrgKTo1UZc4_GqaKTaApJs0tLFuK6Hxqk",
        exercise: "DSZiXAMLHHZBcgFE1oYyJB_OO9-P3nsEI_41dh1MknQ",
        workout: "yxguXXKD_YSnCjC1ILYFBmQ6F20F5dKOoA6hxuqhNUk",
        recipe: "M1t2HaAADGgRVf6bKI1ftUjPChqzrsO9AB5rL0de4wc",
        nutritionalInfo: "3CzfIqBAAVeedeIXG0Bfk_g1AKPcPZotHcmnjmjxS3k",
        podcastShow: "JQ_gsZucnD5aM9V9ue748R5COGFyOZYstGVSm1iX7rU",
        modelProvider: "KiINbVeLPhF795ADmX7LM9oUuI7oAdBm1QtH5Ncj32I",
        conversationSession: "eb6irolDympa5_XENtWMIp_bvQ6CLI9q5arRIBTe2sk",
        multiResolutionGif: "5lqxoSI7DLsl9Q5nqCIsH53r2TUz_Eg6Z56nXc5pk4I",
        organization: "NQi19GjOw-Iv8PzjZ5P-XcFkAYu50cl5V_qceT2xlGM",
        fitnessEquipment: "VEz6iYZ8XpsOHQCOriv7gxyvY0OqyBXrNANCVHEgIsk",
        userFitnessProfile: "wZs4nUUuGnpUyRYM72QYailPb3zfqb4tPsxEE2XWNDk",
        workoutSchedule: "ACgUZxpsxhvy1TaXoOBMBgduje3-d8__gs9nPFSGXWM",
        mealPlan: "aDTATRImcGzgqmuhUK6yXp9KrZpdkoc9Ul05tEMq-W8",
        exerciseResult: "eZFqXh4O5zVqCEs2oNvhi5K3fi8VrTJ9kROVjYmEuxc",
        workoutCompletion: "C3BEhAF0_4Cbblo4CRp8585v6oyaPcgkpiKBp4jWQyw",
        weightEntry: "yXFy2izo1ALbAQOvl8qEQP2XpmMzZoUGXri72I-SKFY",
        shoppingList: "pBI0qarLBP6zPIxBPsl7-ZhzPo0VBqoQ0OFEwZQCUxQ",
        userFitnessAchievment: "-sC601MieajKTLtJfe0ZyT8zxC9SiDrOa8HTP9aOiU0",
        accessControl: "aaZpleo8blkm72kL96UYjTyBPp4F4Wux-Yo3Lu6luvQ",
        music: "rBv4wFs5LUJuMlTkIwXBuZRe3bwZ0KpIoEo3JDsK7ys",
        summaryNutritionalInfoPerServing: "y6Bx-UUGxti0x_o9bni74nA5ykFY2qYyzrzTAoF05rA",
        exerciseMETvalues: "VNMiuJdCoVvQ_5BkCXIySzksCQLqTOs1MogSmmgcNhc",
        notes: "uH3cFr1nyid6KcIXKyox8dKgdh6VG8ugwVaRhDZ5uk8",
        audio: "ku1zNjA19b9zLXR-ujud2L36F61k7Vulj62cMNRwQTE",
        transcriptionEngine: "L_HMK9eKnpS093XRWhZtxN1-4V2D7d_b3XwdjriRcgc",
        noteChunks: "JzU208niezu55f1OwZrBCt_CS0f_PNsW7su0XYpyVSs",
        musicReleaseSimple: "DE0UUdw8-v4IAdMlc1aRy307bHsE15LK_ql8gLTglAw",
        mealPlanDaily: "312xyEZjy4tt6-AHYNYWWTjNQWUAB8rMMCuht9bEUM4"
    },
};